### ISSUE TITLE
Claim check

### ISSUE THREAD

**Issue by lenisko** [bogdal/freepacktbook#11]
Hello there.

What do you think about fetching `https://www.packtpub.com/packt/offers/free-learning` and `https://www.packtpub.com/account/my-ebooks` to check if we don't own new book already just before running Anti-Captcha API request?

**Comment by bogdal** [comment]
Hi. Sure, I think it's a good idea, especially since we have both methods to get the appropriate data.

**Comment by lenisko** [comment]
Even better :-)
