### ISSUE TITLE
Ability to Claim the book to account without downloading it

### ISSUE THREAD

**Issue by rajivvishwa** [bogdal/freepacktbook#4]
Is there a way to claim without downloading the book to local? I was assuming `claim_free_ebook` would only claim the book to our account and `download_ebooks` would actually download them. Looks like it is not the case. 

It would be great if you can add that option

**Comment by bogdal** [comment]
Right now you can simply unset the `PACKTPUB_BOOKS_DIR` environment variable. But I agree with you that `claim_free_ebook` should be more customizable 👍

**Comment by bogdal** [comment]
`freepacktbook 0.0.13` has additional parameters. Right now to download a ebook, the `--download` parameter is required.

More information:

```
claim_free_ebook -h
```
